server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: git@github.com:Senegalion/CityFailurePredictor-ConfigServer.git
          ignoreLocalSshSettings: false
          strictHostKeyChecking: false
          default-label: main
          clone-on-start: true
          refresh-rate: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}