server:
  port: 8082

spring:
  application:
    name: incident-service

  jpa:
    show-sql: false

  datasource:
    url: jdbc:postgresql://postgres-incidents:5432/incidents_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  config:
    label: main
    import: "optional:configserver:http://config-server:8888"

  kafka:
    bootstrap-servers: kafka:9092
    topics:
      incidents-created: incidents.created
      incidents-updated: incidents.updated
    partitions:
      incidents-created: 2
      incidents-updated: 2
    replicas:
      incidents-created: 1
      incidents-updated: 1
    producer:
      acks: all
      retries: 5
      properties:
        enable.idempotence: true
        delivery.timeout.ms: 30000
        request.timeout.ms: 10000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


app:
  kafka:
    topics:
      incidents-created: incidents.created
      incidents-updated: incidents.updated
    partitions:
      incidents-created: 2
      incidents-updated: 2
    replicas:
      incidents-created: 1
      incidents-updated: 1
    producer-timeout-ms: 5000

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

logging:
  level:
    org.hibernate.SQL: WARN
  config: classpath:logback-spring.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}